/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cozy-day-38e5573d832d44279e601687c509f1f0
Title: Cozy Day
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { useFrame, useThree } from '@react-three/fiber';


interface KitchenProps {
  setCurrentStage: any;
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: [number, number, number];
  isRotating: boolean;
  setRotating: (isRotating: boolean) => void;
  onUserInteraction?: () => void;
  onLoad?: () => void;
  setRotationDirection?: (direction: number) => void;
}

const Kitchen = (props: KitchenProps) => {
  const { nodes, materials } = useGLTF('/for-public-page/kitchen.glb');
  const kitchenRef = useRef<THREE.Group>(null);
  const { gl, viewport } = useThree();
  const hasNotifiedLoad = useRef(false);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.55;
  const isKeyboardActive = useRef(false);
  const isPointerDown = useRef(false);

  const handlePointerDown = (e: any) => {
    e.stopPropagation();
    e.preventDefault();
    // Only activate pointer control if keyboard is not active
    if (!isKeyboardActive.current) {
      isPointerDown.current = true;
      props.setRotating(true);
      props.onUserInteraction?.();
      const clientX = 'touches' in e ? e.touches[0].clientX : e.clientX;
      lastX.current = clientX;
    }
  };

  const handlePointerUp = (e: any) => {
    e.stopPropagation();
    e.preventDefault();
    isPointerDown.current = false;
    props.setRotating(false);
  };

  const handlePointerMove = (e: any) => {
    e.stopPropagation();
    e.preventDefault();
    // Only process pointer move if pointer button is actually down and keyboard is not active
    if (isPointerDown.current && !isKeyboardActive.current) {
      const clientX = 'touches' in e ? e.touches[0].clientX : e.clientX;
      const deltaX = (clientX - lastX.current) / viewport.width;
      if (kitchenRef.current) {
        kitchenRef.current.rotation.y += deltaX * Math.PI * 0.005;
      }
      lastX.current = clientX;
      rotationSpeed.current += deltaX * 0.005 * Math.PI;

      // Update rotation direction: positive = clockwise, negative = counter-clockwise
      // Only update if there's significant movement to avoid flickering
      if (props.setRotationDirection && Math.abs(deltaX) > 0.001) {
        props.setRotationDirection(deltaX > 0 ? 1 : -1);
      }
    }
  };

  // Smooth keyboard rotation
  const keyboardRotationSpeed = useRef(0);
  const keyPressed = useRef<string | null>(null);

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
      if (keyPressed.current !== e.key) {
        keyPressed.current = e.key;
        isKeyboardActive.current = true;
        // Force stop pointer-based rotation when keyboard is activated
        props.setRotating(true);
        props.onUserInteraction?.();

        // Start smooth acceleration
        const direction = e.key === 'ArrowLeft' ? 1 : -1;
        const maxSpeed = 0.03; // Maximum rotation speed
        const acceleration = 0.001; // How fast we accelerate

        // Update rotation direction
        if (props.setRotationDirection) {
          props.setRotationDirection(direction);
        }

        const animateKeyboardRotation = () => {
          if (keyPressed.current === e.key && kitchenRef.current) {
            // Gradually increase speed up to max
            keyboardRotationSpeed.current = Math.min(
              keyboardRotationSpeed.current + acceleration,
              maxSpeed
            );

            kitchenRef.current.rotation.y += direction * keyboardRotationSpeed.current;
            requestAnimationFrame(animateKeyboardRotation);
          }
        };

        keyboardRotationSpeed.current = 0.005; // Initial speed
        animateKeyboardRotation();
      }
    }
  };

  const handleKeyUp = (e: KeyboardEvent) => {
    if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
      if (keyPressed.current === e.key) {
        keyPressed.current = null;
        keyboardRotationSpeed.current = 0;
        isKeyboardActive.current = false;
        rotationSpeed.current = 0; // Reset momentum from keyboard rotation

        // Smooth deceleration
        const decelerate = () => {
          if (!keyPressed.current) {
            props.setRotating(false);
          }
        };

        setTimeout(decelerate, 100); // Small delay for smooth stop
      }
    }
  };
  // Function to determine stage based on fixed thresholds
  const getStageFromRotation = (rotation: number): number => {
    // Normalize rotation to [0, 2π] range
    const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

    // Check each threshold boundary - 120° intervals for 3 stages
    const twoPI = 2 * Math.PI;
    const stageAngle = twoPI / 3; // 120° per stage

    if (normalizedRotation >= 0 && normalizedRotation < stageAngle) {
      return 1; // Dashboard: 0° → 120°
    } else if (normalizedRotation >= stageAngle && normalizedRotation < 2 * stageAngle) {
      return 2; // Camera: 120° → 240°
    } else if (normalizedRotation >= 2 * stageAngle && normalizedRotation < twoPI) {
      return 3; // My Experiences: 240° → 360°
    }

    return 1; // Default fallback
  };

  // Notify when loaded
  useEffect(() => {
    if (!hasNotifiedLoad.current && nodes && materials) {
      hasNotifiedLoad.current = true;
      props.onLoad?.();
    }
  }, [nodes, materials, props]);

  useFrame(() => {
    // Handle normal rotation with momentum
    if (!props.isRotating) {
      rotationSpeed.current *= dampingFactor;
      if (Math.abs(rotationSpeed.current) < 0.0001) {
        rotationSpeed.current = 0;
      }
      kitchenRef.current!.rotation.y += rotationSpeed.current;
    }

    // Always check for stage changes based on current rotation
    const rotation = kitchenRef.current?.rotation.y;
    if (rotation !== undefined) {
      const newStage = getStageFromRotation(rotation);
      props.setCurrentStage(newStage);
    }
  });

  useEffect(() => {
    const canvas = gl.domElement;

    const handleTouchStart = (e: TouchEvent) => handlePointerDown(e);
    const handleTouchMove = (e: TouchEvent) => handlePointerMove(e);
    const handleTouchEnd = (e: TouchEvent) => handlePointerUp(e);

    canvas.addEventListener('pointerdown', handlePointerDown);
    canvas.addEventListener('pointermove', handlePointerMove);
    canvas.addEventListener('pointerup', handlePointerUp);
    canvas.addEventListener('touchstart', handleTouchStart);
    canvas.addEventListener('touchmove', handleTouchMove);
    canvas.addEventListener('touchend', handleTouchEnd);
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp);

    return () => {
      canvas.removeEventListener(
      'pointerdown',
      handlePointerDown as unknown as EventListener,
      );
      canvas.removeEventListener(
      'pointermove',
      handlePointerMove as unknown as EventListener,
      );
      canvas.removeEventListener(
      'pointerup',
      handlePointerUp as unknown as EventListener,
      );
      canvas.removeEventListener(
      'touchstart',
      handleTouchStart as unknown as EventListener,
      );
      canvas.removeEventListener(
      'touchmove',
      handleTouchMove as unknown as EventListener,
      );
      canvas.removeEventListener(
      'touchend',
      handleTouchEnd as unknown as EventListener,
      );
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [gl]);

  return (
    <group {...props} ref={kitchenRef}>
      <group position={[-0.15, 0.88, -1.46]} scale={[1, 0.9, 1]}>
        <mesh
          geometry={(nodes.Object_20 as THREE.Mesh).geometry}
          material={materials.big_shapes}
        />
        <mesh
          geometry={(nodes.Object_21 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.87, 2.1, 0]}
        rotation={[0, 0, 1.53]}
        scale={[0.94, 1, 1]}
      >
        <mesh
          geometry={(nodes.Object_27 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
        <mesh
          geometry={(nodes.Object_28 as THREE.Mesh).geometry}
          material={materials.big_shapes}
        />
      </group>
      <group position={[0.35, 0.61, -2.63]} scale={[1, 0.9, 1]}>
        <mesh
          geometry={(nodes.Object_30 as THREE.Mesh).geometry}
          material={materials.big_shapes}
        />
        <mesh
          geometry={(nodes.Object_31 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.91, 1.64, 0.02]} scale={[1, 0.9, 1]}>
        <mesh
          geometry={(nodes.Object_33 as THREE.Mesh).geometry}
          material={materials.big_shapes}
        />
        <mesh
          geometry={(nodes.Object_34 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[0.77, 1.23, -1.43]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.17, 1, 0.89]}
      >
        <mesh
          geometry={(nodes.Object_36 as THREE.Mesh).geometry}
          material={materials.big_shapes}
        />
        <mesh
          geometry={(nodes.Object_37 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.84, 3.08, -1.42]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1, 1, 0.79]}
      >
        <mesh
          geometry={(nodes.Object_53 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_54 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.8, 2.67, -0.97]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1, 1, 0.73]}
      >
        <mesh
          geometry={(nodes.Object_56 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_57 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.78, 3.14, -0.94]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh
          geometry={(nodes.Object_59 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_60 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.84, 2.5, -1.54]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.8}
      >
        <mesh
          geometry={(nodes.Object_62 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_63 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.85, 2.47, -1.7]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={(nodes.Object_65 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_66 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.85, 2.39, -1.41]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={(nodes.Object_68 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_69 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.25, 2, -1.12]} rotation={[-Math.PI, 1.19, 0]}>
        <mesh
          geometry={(nodes.Object_71 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_72 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.28, 1.99, -1.4]} rotation={[-Math.PI, 1.09, 0]}>
        <mesh
          geometry={(nodes.Object_74 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_75 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.01, 1.98, -1.07]} rotation={[-Math.PI, 1.36, 0]}>
        <mesh
          geometry={(nodes.Object_77 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_78 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.69, 2.79, 2.22]} rotation={[1.65, -0.05, -0.01]}>
        <mesh
          geometry={(nodes.Object_80 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_81 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.68, 2.61, 2.22]} rotation={[1.63, 0.02, -0.02]}>
        <mesh
          geometry={(nodes.Object_83 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_84 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.78, 3.43, -1.05]} rotation={[0.8, 0, Math.PI / 2]}>
        <mesh
          geometry={(nodes.Object_86 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_87 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.78, 3.44, -1.79]} rotation={[-1.47, 0, 1.59]}>
        <mesh
          geometry={(nodes.Object_89 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_90 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.77, 2.75, -1.81]} rotation={[-2.2, 0, 1.59]}>
        <mesh
          geometry={(nodes.Object_92 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_93 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.77, 2.87, -1.15]} rotation={[2.53, 0, Math.PI / 2]}>
        <mesh
          geometry={(nodes.Object_95 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_96 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.64, 2.57, 1.05]} rotation={[1.55, 0.07, -0.01]}>
        <mesh
          geometry={(nodes.Object_98 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_99 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.63, 2.52, 1.05]} rotation={[1.61, 0.08, -0.01]}>
        <mesh
          geometry={(nodes.Object_101 as THREE.Mesh).geometry}
          material={materials.notes}
        />
        <mesh
          geometry={(nodes.Object_102 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.62, 2.74, 1.6]}>
        <mesh
          geometry={(nodes.Object_104 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_105 as THREE.Mesh).geometry}
          material={materials.big_shapes}
        />
      </group>
      <group position={[0.36, 0.61, 1.41]}>
        <mesh
          geometry={(nodes.Object_107 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_108 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.15, 0.8, 1.89]} rotation={[0.57, 1.34, -0.77]}>
        <mesh
          geometry={(nodes.Object_110 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_111 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.19, 1.43, 1.67]}>
        <mesh
          geometry={(nodes.Object_113 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_114 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.91, 1.63, 0.02]}>
        <mesh
          geometry={(nodes.Object_116 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_117 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.48, 2.26, -0.3]}>
        <mesh
          geometry={(nodes.Object_119 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_120 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.24, 2.33, 0.32]}>
        <mesh
          geometry={(nodes.Object_122 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_123 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.22, 2.22, -0.32]}>
        <mesh
          geometry={(nodes.Object_125 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_126 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.38, 2.22, -1.63]}>
        <mesh
          geometry={(nodes.Object_128 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_129 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.25, 2.02, -1.82]}>
        <mesh
          geometry={(nodes.Object_131 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_132 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.05, 2.01, -1.68]}>
        <mesh
          geometry={(nodes.Object_134 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_135 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.25, 2.2, -1.82]}>
        <mesh
          geometry={(nodes.Object_137 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_138 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.25, 2.22, -1.82]} rotation={[0.07, 0.03, -0.05]}>
        <mesh
          geometry={(nodes.Object_140 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_141 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.74, 2.67, 0.32]} rotation={[1.57, 0, -1.57]}>
        <mesh
          geometry={(nodes.Object_143 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_144 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.7, 2.99, 0.32]} rotation={[-0.04, -0.01, 0.01]}>
        <mesh
          geometry={(nodes.Object_146 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_147 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.29, 2.42, -0.37]}
        rotation={[-0.03, -0.37, 0.17]}
        scale={0.93}
      >
        <mesh
          geometry={(nodes.Object_149 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_150 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.48, 2.49, -0.3]} rotation={[0.12, -0.6, 0.11]}>
        <mesh
          geometry={(nodes.Object_152 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_153 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.64, 3.47, 1.23]} rotation={[0, 1.39, 0]}>
        <mesh
          geometry={(nodes.Object_155 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_156 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.71, 3.42, 1.69]}>
        <mesh
          geometry={(nodes.Object_158 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_159 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.74, 3.53, 1.71]} rotation={[0.15, -0.21, 0.04]}>
        <mesh
          geometry={(nodes.Object_161 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_162 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.75, 3.56, 1.68]} rotation={[-0.02, 0.04, 0.27]}>
        <mesh
          geometry={(nodes.Object_164 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_165 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.58, 2.87, -0.05]}
        rotation={[-0.03, 0.4, -1.2]}
        scale={1.32}
      >
        <mesh
          geometry={(nodes.Object_167 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_168 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.61, 2.87, -0.06]} rotation={[-0.08, 0.38, -1.27]}>
        <mesh
          geometry={(nodes.Object_170 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_171 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.59, 2.81, -0.32]} rotation={[-0.07, 0.05, -1.3]}>
        <mesh
          geometry={(nodes.Object_173 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_174 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.66, 3.5, 1.47]} scale={0.94}>
        <mesh
          geometry={(nodes.Object_178 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_179 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.55, 2.82, 1.81]}>
        <mesh
          geometry={(nodes.Object_185 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_186 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.6, 3.1, 1.2]}>
        <mesh
          geometry={(nodes.Object_190 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_191 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.59, 2.83, 1.5]}>
        <mesh
          geometry={(nodes.Object_193 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_194 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.62, 2.38, 1.95]}>
        <mesh
          geometry={(nodes.Object_198 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_199 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.58, 2.14, 1.45]}>
        <mesh
          geometry={(nodes.Object_201 as THREE.Mesh).geometry}
          material={materials.details_non_culled}
        />
        <mesh
          geometry={(nodes.Object_202 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.38, 2.43, -1.63]} rotation={[0.02, -0.62, 0.02]}>
        <mesh
          geometry={(nodes.Object_206 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_207 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.14, 2.06, -1.69]}>
        <mesh
          geometry={(nodes.Object_209 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_210 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.22, 2.04, -1.71]}>
        <mesh
          geometry={(nodes.Object_212 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_213 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.25, 2.01, -1.17]} rotation={[0, -1.08, 0]}>
        <mesh
          geometry={(nodes.Object_215 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_216 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.7, 3.39, -0.23]}
        rotation={[0.05, -0.1, -1.58]}
        scale={1.08}
      >
        <mesh
          geometry={(nodes.Object_218 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_219 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.69, 3.36, 0.34]} rotation={[-1.68, 0, -0.7]}>
        <mesh
          geometry={(nodes.Object_221 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_222 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.81, 3.52, 0.36]}>
        <mesh
          geometry={(nodes.Object_224 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_225 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.81, 3.52, -0.21]}>
        <mesh
          geometry={(nodes.Object_227 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_228 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.66, 3.71, 1.47]} rotation={[0.02, 0, 0.07]}>
        <mesh
          geometry={(nodes.Object_234 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_235 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.64, 3.54, 1.23]} rotation={[0, -0.62, 0.01]}>
        <mesh
          geometry={(nodes.Object_237 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_238 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.66, 3.46, 1.05]}>
        <mesh
          geometry={(nodes.Object_240 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_241 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.61, 1.5, 2.04]}>
        <mesh
          geometry={(nodes.Object_245 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_246 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.6, 1.68, 1.99]} rotation={[-0.19, 0, -0.18]}>
        <mesh
          geometry={(nodes.Object_248 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_249 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.74, 0.84, -2.63]} rotation={[-1.4, 0.49, -1.59]}>
        <mesh
          geometry={(nodes.Object_253 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_254 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.79, 0.22, 0.62]}>
        <mesh
          geometry={(nodes.Object_256 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_257 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.79, 0.22, -0.58]}>
        <mesh
          geometry={(nodes.Object_259 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_260 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.23, 2.37, 0.54]} rotation={[2.68, -1.54, 1.3]}>
        <mesh
          geometry={(nodes.Object_264 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_265 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.26, 2.51, 0.18]}>
        <mesh
          geometry={(nodes.Object_267 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_268 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.68, 2.84, 1.68]}>
        <mesh
          geometry={(nodes.Object_274 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_275 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.68, 3.03, 1.68]}>
        <mesh
          geometry={(nodes.Object_277 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_278 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.44, 2.05, -0.31]}>
        <mesh
          geometry={(nodes.Object_282 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_283 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.38, 2.39, -1.63]}>
        <mesh
          geometry={(nodes.Object_285 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_286 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.64, 3.51, 1.23]}>
        <mesh
          geometry={(nodes.Object_288 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_289 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.55, 2.89, 1.81]}>
        <mesh
          geometry={(nodes.Object_291 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_292 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.6, 2.87, -0.34]} rotation={[-0.35, 0.15, -0.9]}>
        <mesh
          geometry={(nodes.Object_294 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_295 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.21, 1.37, 1.64]}>
        <mesh
          geometry={(nodes.Object_299 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_300 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.24, 1.33, 1.63]}>
        <mesh
          geometry={(nodes.Object_302 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_303 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.19, 1.28, 1.66]}>
        <mesh
          geometry={(nodes.Object_305 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_306 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.61, 1.35, 2.04]}>
        <mesh
          geometry={(nodes.Object_308 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_309 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[0.86, 1.9, 0.16]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={(nodes.Object_311 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_312 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[0.86, 1.9, -0.11]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={(nodes.Object_314 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_315 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[0.86, 1.9, -0.38]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={(nodes.Object_317 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_318 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.68, 3.09, 1.68]} rotation={[0, -0.62, 0]}>
        <mesh
          geometry={(nodes.Object_320 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_321 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.14, 0.73, 1.9]} rotation={[0, -0.02, -0.07]}>
        <mesh
          geometry={(nodes.Object_323 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_324 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.14, 0.69, 1.9]} rotation={[-0.02, -0.01, -0.03]}>
        <mesh
          geometry={(nodes.Object_326 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_327 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.69, 3.41, -0.24]} rotation={[-1.72, -0.06, -1.15]}>
        <mesh
          geometry={(nodes.Object_329 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_330 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.05, 2.18, -1.68]} rotation={[-0.08, -0.62, -0.08]}>
        <mesh
          geometry={(nodes.Object_332 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_333 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.47, 2.53, -0.31]} rotation={[0.21, -0.73, 0.32]}>
        <mesh
          geometry={(nodes.Object_335 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_336 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.55, 3.41, 1.98]}>
        <mesh
          geometry={(nodes.Object_340 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_341 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.6, 3.1, 1.2]}>
        <mesh
          geometry={(nodes.Object_347 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_348 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.62, 2.38, 1.95]}>
        <mesh
          geometry={(nodes.Object_352 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_353 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[0.86, 1.9, 0.16]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={(nodes.Object_355 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_356 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[0.86, 1.9, -0.1]}
        rotation={[1.54, -0.01, -1.65]}
        scale={0.96}
      >
        <mesh
          geometry={(nodes.Object_358 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_359 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[0.86, 1.9, -0.38]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.01}
      >
        <mesh
          geometry={(nodes.Object_361 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_362 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.21, 2.04, 1.71]}
        rotation={[Math.PI, -1.31, Math.PI]}
        scale={0.42}
      >
        <mesh
          geometry={(nodes.Object_368 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_369 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.61, 2.27, 1.46]} rotation={[-0.03, 0.71, 0.28]}>
        <mesh
          geometry={(nodes.Object_371 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_372 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[0.86, 1.9, 0.41]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={(nodes.Object_406 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_407 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.79, 0.22, 0.62]}>
        <mesh
          geometry={(nodes.Object_417 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_418 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.79, 0.22, -0.58]}>
        <mesh
          geometry={(nodes.Object_420 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_421 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.58, 2.2, 1.94]} scale={0.99}>
        <mesh
          geometry={(nodes.Object_425 as THREE.Mesh).geometry}
          material={materials.details}
        />
        <mesh
          geometry={(nodes.Object_426 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.26, 1.02, -2.71]} rotation={[0.07, -0.04, -1.09]}>
        <mesh
          geometry={(nodes.Object_436 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_437 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.23, 0.95, -2.83]} rotation={[-0.39, -0.45, -0.83]}>
        <mesh
          geometry={(nodes.Object_439 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_440 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.27, 1.36, -2.61]} rotation={[-2.99, -1.26, 2.49]}>
        <mesh
          geometry={(nodes.Object_442 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_443 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.51, 1.37, -2.84]} rotation={[-3.09, -0.37, 2.36]}>
        <mesh
          geometry={(nodes.Object_445 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_446 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.39, 0.82, -2.59]} rotation={[-0.01, -0.28, -1.81]}>
        <mesh
          geometry={(nodes.Object_448 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_449 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.61, 1.53, -3.07]} rotation={[-1.16, -0.51, -2.11]}>
        <mesh
          geometry={(nodes.Object_451 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_452 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.5, 1.02, -2.54]} rotation={[3.13, -0.03, 2.35]}>
        <mesh
          geometry={(nodes.Object_454 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_455 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.36, 0.96, -2.77]} rotation={[-2.7, -0.84, 3.12]}>
        <mesh
          geometry={(nodes.Object_457 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_458 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.47, 1.12, -2.46]} rotation={[-2.36, 0.15, 2.84]}>
        <mesh
          geometry={(nodes.Object_460 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_461 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.37, 0.97, -2.32]} rotation={[2.92, 0.97, 2.11]}>
        <mesh
          geometry={(nodes.Object_463 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_464 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.34, 1.1, -2.85]} rotation={[-0.17, -1.05, -0.94]}>
        <mesh
          geometry={(nodes.Object_466 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_467 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[0.19, 1.13, -2.86]} rotation={[0.11, 0.49, -0.45]}>
        <mesh
          geometry={(nodes.Object_469 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_470 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[-0.29, 2.32, -1.15]} rotation={[0.13, 0.12, 0.26]}>
        <mesh
          geometry={(nodes.Object_476 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_477 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.09, 2.25, 1.81]}
        rotation={[2.5, 0.97, 0.98]}
        scale={[-0.25, 0.25, 0.25]}
      >
        <mesh
          geometry={(nodes.Object_479 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_480 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[0.25, 1.77, 2.43]}
        rotation={[0.99, 0, 2.34]}
        scale={0.45}
      >
        <mesh
          geometry={(nodes.Object_482 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_483 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[0.39, 1.99, 2.36]}
        rotation={[1.42, 0.07, 2.29]}
        scale={0.45}
      >
        <mesh
          geometry={(nodes.Object_485 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_486 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[0.07, 2.12, 2.12]}
        rotation={[0.38, 0.3, 2.79]}
        scale={0.44}
      >
        <mesh
          geometry={(nodes.Object_488 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_489 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[0.31, 1.68, 2.36]}
        rotation={[1.72, 0.32, 2.04]}
        scale={0.44}
      >
        <mesh
          geometry={(nodes.Object_491 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_492 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[0.36, 1.56, 2.47]}
        rotation={[1.14, 0.13, -3]}
        scale={0.43}
      >
        <mesh
          geometry={(nodes.Object_494 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_495 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[0.27, 0.17, 2.5]}
        rotation={[0.02, -0.13, 2.88]}
        scale={[0.29, 0.43, 0.44]}
      >
        <mesh
          geometry={(nodes.Object_497 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_498 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[0.33, 0.27, 2.35]}
        rotation={[0.37, 0.5, -3]}
        scale={[0.4, 0.45, 0.45]}
      >
        <mesh
          geometry={(nodes.Object_500 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_501 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[0.2, 0.51, 2.41]}
        rotation={[0.74, 0.22, 2.75]}
        scale={0.4}
      >
        <mesh
          geometry={(nodes.Object_503 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_504 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.38, 2.73, 1.76]}
        rotation={[0.97, 0.53, 2.71]}
        scale={0.43}
      >
        <mesh
          geometry={(nodes.Object_506 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_507 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[-0.48, 2.85, 1.7]}
        rotation={[2.45, 1.08, 0.77]}
        scale={0.26}
      >
        <mesh
          geometry={(nodes.Object_509 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_510 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.3, 2.58, 1.69]}
        rotation={[2.03, 1.07, 1.49]}
        scale={[-0.29, 0.29, 0.29]}
      >
        <mesh
          geometry={(nodes.Object_512 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_513 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.61, 2.89, 1.46]}
        rotation={[-1.7, 0.12, 2.28]}
        scale={0.29}
      >
        <mesh
          geometry={(nodes.Object_515 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_516 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.59, 2.89, 1.48]}
        rotation={[-2.04, 0.29, 2.16]}
        scale={0.26}
      >
        <mesh
          geometry={(nodes.Object_518 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_519 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.61, 2.93, 1.5]}
        rotation={[-0.91, -0.62, 1.84]}
        scale={0.29}
      >
        <mesh
          geometry={(nodes.Object_521 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_522 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.6, 2.98, 1.49]}
        rotation={[-1.53, -0.43, 1.68]}
        scale={0.2}
      >
        <mesh
          geometry={(nodes.Object_524 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_525 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.54, 2.89, 1.49]}
        rotation={[-1.32, 0.22, 1.43]}
        scale={0.26}
      >
        <mesh
          geometry={(nodes.Object_527 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_528 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.53, 2.92, 1.56]}
        rotation={[-0.71, -0.55, 1.87]}
        scale={0.19}
      >
        <mesh
          geometry={(nodes.Object_530 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_531 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group position={[0.3, 2.36, -1.84]} rotation={[-0.88, -0.48, -0.58]}>
        <mesh
          geometry={(nodes.Object_533 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_534 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group
        position={[0.17, 0.78, 2.22]}
        rotation={[0.92, 0.84, 2]}
        scale={0.46}
      >
        <mesh
          geometry={(nodes.Object_536 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_537 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.2, 0.87, 2.09]}
        rotation={[-0.61, -0.06, 2.58]}
        scale={0.29}
      >
        <mesh
          geometry={(nodes.Object_539 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_540 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.01, 0.82, 1.86]}
        rotation={[-1.57, 0.54, -2.16]}
        scale={0.29}
      >
        <mesh
          geometry={(nodes.Object_542 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_543 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.05, 0.8, 1.94]}
        rotation={[-0.57, 0.38, -2.98]}
        scale={0.29}
      >
        <mesh
          geometry={(nodes.Object_545 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_546 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.06, 0.82, 1.92]}
        rotation={[-1.24, -0.47, 1.74]}
        scale={0.29}
      >
        <mesh
          geometry={(nodes.Object_548 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_549 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[0, 0.82, 1.9]}
        rotation={[-2.34, 1.11, -0.51]}
        scale={0.26}
      >
        <mesh
          geometry={(nodes.Object_551 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_552 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group
        position={[-0.13, 0.84, 2.04]}
        rotation={[-0.7, 0.2, 2.02]}
        scale={0.22}
      >
        <mesh
          geometry={(nodes.Object_554 as THREE.Mesh).geometry}
          material={materials.leaves}
        />
        <mesh
          geometry={(nodes.Object_555 as THREE.Mesh).geometry}
          material={materials.outline_non_culled}
        />
      </group>
      <group position={[0.7, 2.38, -0.4]} rotation={[0, -0.02, 0]}>
        <mesh
          geometry={(nodes.Object_557 as THREE.Mesh).geometry}
          material={materials.Material}
        />
        <mesh
          geometry={(nodes.Object_558 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[2.03, 0.5, 0.49]} rotation={[-0.11, 0, -0.04]}>
        <mesh
          geometry={(nodes.Object_566 as THREE.Mesh).geometry}
          material={materials.catsu}
        />
        <mesh
          geometry={(nodes.Object_567 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[2.22, 0.34, 1.02]} rotation={[0.87, 0.23, -0.16]}>
        <mesh
          geometry={(nodes.Object_571 as THREE.Mesh).geometry}
          material={materials.catsu}
        />
        <mesh
          geometry={(nodes.Object_572 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[2.23, 0.44, 0.97]} rotation={[0.05, -0.77, -1.2]}>
        <mesh
          geometry={(nodes.Object_574 as THREE.Mesh).geometry}
          material={materials.catsu}
        />
        <mesh
          geometry={(nodes.Object_575 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <group position={[2.13, 0.34, 1.1]} rotation={[1.31, -0.46, -0.13]}>
        <mesh
          geometry={(nodes.Object_577 as THREE.Mesh).geometry}
          material={materials.catsu}
        />
        <mesh
          geometry={(nodes.Object_578 as THREE.Mesh).geometry}
          material={materials.outline_culled}
        />
      </group>
      <mesh
        geometry={(nodes.Object_4 as THREE.Mesh).geometry}
        material={materials.outline_non_culled}
      />
      <mesh
        geometry={(nodes.Object_6 as THREE.Mesh).geometry}
        material={materials.white}
      />
      <mesh
        geometry={(nodes.Object_8 as THREE.Mesh).geometry}
        material={materials.white}
      />
      <mesh
        geometry={(nodes.Object_10 as THREE.Mesh).geometry}
        material={materials.white}
      />
      <mesh
        geometry={(nodes.Object_12 as THREE.Mesh).geometry}
        material={materials.white}
      />
      <mesh
        geometry={(nodes.Object_14 as THREE.Mesh).geometry}
        material={materials.white}
        position={[7.28, 2.52, -5.46]}
        scale={0.64}
      />
      <mesh
        geometry={(nodes.Object_16 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[7.28, 2.52, -5.46]}
        scale={0.64}
      />
      <mesh
        geometry={(nodes.Object_18 as THREE.Mesh).geometry}
        material={materials.big_shapes}
        position={[0, 0.87, 0]}
        scale={[1, 0.92, 1]}
      />
      <mesh
        geometry={(nodes.Object_23 as THREE.Mesh).geometry}
        material={materials.big_shapes}
        position={[0, 1.98, 1.57]}
        scale={[1, 0.9, 1]}
      />
      <mesh
        geometry={(nodes.Object_25 as THREE.Mesh).geometry}
        material={materials.big_shapes}
        position={[0, 0.51, 1.57]}
        scale={[1, 0.9, 1]}
      />
      <mesh
        geometry={(nodes.Object_39 as THREE.Mesh).geometry}
        material={materials.floor_n_mattress}
        position={[2.29, 0.15, 0.58]}
        scale={0.82}
      />
      <mesh
        geometry={(nodes.Object_41 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[0, 1.98, 1.57]}
        scale={[1, 0.9, 1]}
      />
      <mesh
        geometry={(nodes.Object_43 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[0, 0.51, 1.57]}
        scale={[1, 0.9, 1]}
      />
      <mesh
        geometry={(nodes.Object_45 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[0, 0.87, 0]}
        scale={[1, 0.92, 1]}
      />
      <mesh
        geometry={(nodes.Object_47 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.15, 0.88, -1.46]}
        scale={[1, 0.9, 1]}
      />
      <mesh
        geometry={(nodes.Object_49 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[2.29, 0.15, 0.58]}
        scale={0.82}
      />
      <mesh
        geometry={(nodes.Object_51 as THREE.Mesh).geometry}
        material={materials.outline_non_culled}
        position={[2.29, 0.15, 0.58]}
        scale={0.82}
      />
      <mesh
        geometry={(nodes.Object_176 as THREE.Mesh).geometry}
        material={materials.details}
        position={[0.33, 2.13, 1.43]}
        rotation={[0, 0.24, 0]}
      />
      <mesh
        geometry={(nodes.Object_181 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.62, 2.88, 2]}
      />
      <mesh
        geometry={(nodes.Object_183 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.61, 3.08, 2.04]}
      />
      <mesh
        geometry={(nodes.Object_188 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.62, 2.88, 1.21]}
      />
      <mesh
        geometry={(nodes.Object_196 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.58, 2.2, 1.94]}
        scale={0.99}
      />
      <mesh
        geometry={(nodes.Object_204 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.57, 2.18, 1.67]}
      />
      <mesh
        geometry={(nodes.Object_230 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.55, 2.26, 1.22]}
      />
      <mesh
        geometry={(nodes.Object_232 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.55, 2.52, 1.22]}
        rotation={[0.11, 0.21, -0.03]}
      />
      <mesh
        geometry={(nodes.Object_243 as THREE.Mesh).geometry}
        material={materials.details_non_culled}
        position={[-0.6, 2.39, 1.7]}
      />
      <mesh
        geometry={(nodes.Object_251 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.55, 3.41, 1.98]}
      />
      <mesh
        geometry={(nodes.Object_262 as THREE.Mesh).geometry}
        material={materials.notes}
        position={[-0.76, 3.26, -0.93]}
        rotation={[-0.23, 0.48, -0.89]}
      />
      <mesh
        geometry={(nodes.Object_270 as THREE.Mesh).geometry}
        material={materials.details}
        position={[0.43, 2.13, 1.83]}
        rotation={[1.46, -0.26, -0.22]}
      />
      <mesh
        geometry={(nodes.Object_272 as THREE.Mesh).geometry}
        material={materials.details}
        position={[0.24, 2.14, 1.04]}
        rotation={[1.66, -0.23, -0.19]}
      />
      <mesh
        geometry={(nodes.Object_280 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.55, 2.25, 1.22]}
      />
      <mesh
        geometry={(nodes.Object_297 as THREE.Mesh).geometry}
        material={materials.details_non_culled}
        position={[-0.61, 2.4, 1.65]}
      />
      <mesh
        geometry={(nodes.Object_338 as THREE.Mesh).geometry}
        material={materials.details}
        position={[0.37, 2.03, 1.41]}
        rotation={[0, 0.37, 0]}
      />
      <mesh
        geometry={(nodes.Object_343 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.62, 2.88, 2]}
      />
      <mesh
        geometry={(nodes.Object_345 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.61, 3.08, 2.04]}
      />
      <mesh
        geometry={(nodes.Object_350 as THREE.Mesh).geometry}
        material={materials.details}
        position={[-0.62, 2.89, 1.21]}
      />
      <mesh
        geometry={(nodes.Object_364 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.58, 2.2, 1.94]}
      />
      <mesh
        geometry={(nodes.Object_366 as THREE.Mesh).geometry}
        material={materials.details}
        position={[0.47, 2.04, 1.82]}
        rotation={[0, 0.37, 0]}
        scale={0.42}
      />
      <mesh
        geometry={(nodes.Object_374 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.62, 2.74, 1.6]}
      />
      <mesh
        geometry={(nodes.Object_376 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.55, 2.25, 1.22]}
      />
      <mesh
        geometry={(nodes.Object_378 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.55, 2.25, 1.22]}
      />
      <mesh
        geometry={(nodes.Object_380 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.55, 2.26, 1.22]}
      />
      <mesh
        geometry={(nodes.Object_382 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.55, 2.52, 1.22]}
        rotation={[0.11, 0.21, -0.03]}
      />
      <mesh
        geometry={(nodes.Object_384 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.62, 2.88, 1.21]}
        scale={1.03}
      />
      <mesh
        geometry={(nodes.Object_386 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.62, 2.89, 1.21]}
      />
      <mesh
        geometry={(nodes.Object_388 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.62, 2.89, 1.21]}
      />
      <mesh
        geometry={(nodes.Object_390 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.57, 2.18, 1.67]}
      />
      <mesh
        geometry={(nodes.Object_392 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[0.37, 2.03, 1.41]}
        rotation={[0, 0.37, 0]}
      />
      <mesh
        geometry={(nodes.Object_394 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[0.47, 2.04, 1.82]}
        rotation={[0, 0.37, 0]}
        scale={0.42}
      />
      <mesh
        geometry={(nodes.Object_396 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[0.24, 2.14, 1.04]}
        rotation={[1.66, -0.23, -0.19]}
      />
      <mesh
        geometry={(nodes.Object_398 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.62, 2.88, 2]}
      />
      <mesh
        geometry={(nodes.Object_400 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.62, 2.88, 2]}
      />
      <mesh
        geometry={(nodes.Object_402 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.61, 3.08, 2.04]}
      />
      <mesh
        geometry={(nodes.Object_404 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.61, 3.08, 2.04]}
      />
      <mesh
        geometry={(nodes.Object_409 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.55, 3.41, 1.98]}
      />
      <mesh
        geometry={(nodes.Object_411 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.55, 3.41, 1.98]}
        scale={0.99}
      />
      <mesh
        geometry={(nodes.Object_413 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[0.24, 2.14, 1.04]}
        rotation={[1.66, -0.23, -0.19]}
      />
      <mesh
        geometry={(nodes.Object_415 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[0.33, 2.13, 1.43]}
        rotation={[0, 0.24, 0]}
      />
      <mesh
        geometry={(nodes.Object_423 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.58, 2.2, 1.94]}
      />
      <mesh
        geometry={(nodes.Object_428 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.58, 2.2, 1.94]}
        scale={0.99}
      />
      <mesh
        geometry={(nodes.Object_430 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.61, 2.4, 1.65]}
      />
      <mesh
        geometry={(nodes.Object_432 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.6, 2.39, 1.7]}
      />
      <mesh
        geometry={(nodes.Object_434 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.76, 3.26, -0.93]}
        rotation={[-0.23, 0.48, -0.89]}
      />
      <mesh
        geometry={(nodes.Object_472 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.63, 2.8, 1.47]}
        rotation={[-2.79, 0.43, 1.62]}
        scale={0.09}
      />
      <mesh
        geometry={(nodes.Object_474 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[-0.04, 0.82, 1.91]}
        rotation={[3, 0.42, 2.01]}
        scale={0.08}
      />
      <mesh
        geometry={(nodes.Object_560 as THREE.Mesh).geometry}
        material={materials.Material}
        position={[0.71, 2.03, -0.52]}
        rotation={[Math.PI, -1.37, Math.PI]}
      />
      <mesh
        geometry={(nodes.Object_562 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[0.71, 2.03, -0.52]}
        rotation={[Math.PI, -1.37, Math.PI]}
      />
      <mesh
        geometry={(nodes.Object_564 as THREE.Mesh).geometry}
        material={materials.floor_n_mattress}
        position={[-0.11, 0.16, -0.11]}
      />
      <mesh
        geometry={(nodes.Object_569 as THREE.Mesh).geometry}
        material={materials.catsu}
        position={[2.04, 0.16, 1.11]}
        rotation={[-2.38, -0.93, -2]}
      />
      <mesh
        geometry={(nodes.Object_580 as THREE.Mesh).geometry}
        material={materials.catsu}
        position={[2.35, 0.32, 0.18]}
        rotation={[0.06, 0.03, 0.08]}
      />
      <mesh
        geometry={(nodes.Object_582 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[2.04, 0.16, 1.1]}
        rotation={[-2.38, -0.93, -2]}
      />
      <mesh
        geometry={(nodes.Object_584 as THREE.Mesh).geometry}
        material={materials.outline_culled}
        position={[2.36, 0.36, 0.09]}
        rotation={[0.06, 0.03, 0.08]}
        scale={1.06}
      />
    </group>
  );
};

Kitchen.displayName = 'Kitchen';

export default Kitchen;
